# Generated by Django 3.0.7 on 2020-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalwatchlist',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='auctions_in_the_watchlist', to='auctions.Auction'),
        ),
    ]
