# Generated by Django 3.0.7 on 2020-10-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_delete_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='img_url',
        ),
    ]
