# Generated by Django 3.0.7 on 2020-10-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auction_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
